import type { JobRole } from "../models/job-role.js";

export function createSampleJobRoles(): JobRole[] {
  return [
    {
      id: "1",
      roleName: "Senior Software Engineer",
      location: "London",
      capability: "Backend Development",
      band: "Senior",
      closingDate: new Date("2025-11-15"),
    },
    {
      id: "2",
      roleName: "Junior Frontend Developer",
      location: "Manchester",
      capability: "Frontend Development",
      band: "Junior",
      closingDate: new Date("2025-10-30"),
    },
    {
      id: "3",
      roleName: "DevOps Engineer",
      location: "Birmingham",
      capability: "Infrastructure",
      band: "Mid",
      closingDate: new Date("2025-12-01"),
    },
    {
      id: "4",
      roleName: "Product Manager",
      location: "Edinburgh",
      capability: "Product Management",
      band: "Senior",
      closingDate: new Date("2025-11-20"),
    },
    {
      id: "5",
      roleName: "UX Designer",
      location: "Bristol",
      capability: "Design",
      band: "Mid",
      closingDate: new Date("2025-10-25"),
    },
    {
      id: "6",
      roleName: "Data Scientist",
      location: "Cambridge",
      capability: "Data & Analytics",
      band: "Senior",
      closingDate: new Date("2025-12-10"),
    },
    {
      id: "7",
      roleName: "Junior QA Engineer",
      location: "Leeds",
      capability: "Quality Assurance",
      band: "Junior",
      closingDate: new Date("2025-11-05"),
    },
    {
      id: "8",
      roleName: "Technical Lead",
      location: "Glasgow",
      capability: "Engineering Leadership",
      band: "Principal",
      closingDate: new Date("2025-12-15"),
    },
    {
      id: "9",
      roleName: "Mobile Developer",
      location: "Cardiff",
      capability: "Mobile Development",
      band: "Mid",
      closingDate: new Date("2025-11-25"),
    },
    {
      id: "10",
      roleName: "Cybersecurity Specialist",
      location: "Belfast",
      capability: "Security",
      band: "Senior",
      closingDate: new Date("2025-12-05"),
    },
  ];
}
